[project]
name = "dsait4205-control-dataset"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "pillow>=11.2.1",
    "scikit-learn>=1.7.0",
]
